dependencies {
	compileOnly group: "com.liferay.portal", name: "release.portal.api"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
    compileOnly group: "org.osgi", name: "org.osgi.service.metatype.annotations", version: "1.4.0"
    
	implementation project(":modules:challenge-service:challenge-service-api")
	implementation project(":modules:challenge-service:challenge-service-service")
	


	cssBuilder group: "com.liferay", name: "com.liferay.css.builder", version: "3.1.4"
	
}